name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, task-1, task-2, task-3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pipeline or tests
      run: |
        dvc status  # Check if data is up to date
        # Or run your Python scripts here
        # e.g., python src/main.py
